go.property('panSpeed', 6)
go.property('pivot', 80)
go.property('verticalspeed', 10) -- set to 0 to disable vertical movement
go.property('snapCursor', true)
go.property('maxHigh', 1500)
go.property('window_width', 1920)
go.property('window_height', 1080)

-- Variables to control camera movement
local sensitivity = 0.01 -- Adjust this value to control the mouse self.sensitivity
local rotation_speed = 0.05 -- Adjust this value to control the camera rotation speed

local illum = require "illumination.illumination"
--print("Illum name:", illum and "OK" or "nil")

-- Variables to track camera rotation
local pitch = 0
local yaw = 0
local work = 0

function init(self)	
	msg.post(".", "acquire_input_focus") -- Acquire input focus for the script
	msg.post("#camera", "acquire_camera_focus") -- Acquire camera focus

	self.hor = 0
	self.camhor = 0
	self.camdepth = 0
	self.depth = 0
	self.lean = 0
	self.tilt = 0
	self.updown = 0
	self.sprint = 1
	self.selected = hash('')
	local pos = go.get_position()
end

function update(self, dt)
	-- * -- -- Panning controls -- -- * --
	local position = go.get_position()

	position.y = position.y+(self.verticalspeed*dt*self.updown)
	if position.y < 1 then position.y = 1 elseif
		position.y > self.maxHigh then position.y = self.maxHigh 
	end

	local eulerz = go.get('.', 'euler.y')
	local eulerz_rad = math.rad(eulerz) -- Convert degrees to radians

	if self.lean ~= 0 then
		eulerz = eulerz + (self.pivot * dt) * self.lean
		go.set('.', 'euler.y', eulerz)
	end

	if self.tilt ~= 0 then
		local eulerx = go.get('.', 'euler.x')
		eulerx = eulerx+(self.pivot*dt)*self.tilt
		go.set('.', 'euler.x', eulerx)
	end

	local forward = vmath.rotate(vmath.quat_rotation_y(eulerz_rad), vmath.vector3(0, 0, 1))
	local right = vmath.rotate(vmath.quat_rotation_y(eulerz_rad), vmath.vector3(1, 0, 0))

	position = position +  ( ((self.hor+self.camhor*2) * right + (self.depth+self.camdepth*2) * forward) * (self.panSpeed*3 * dt * self.sprint) )
	go.set_position(position)
end

function on_input(self, action_id, action)
	if not action_id then
		-- Check if the mouse is at the edge of the screen
		local scroll_left = action.x < 0.05 * self.window_width
		local scroll_right = action.x > 0.95 * self.window_width
		local scroll_up = action.y < 0.05 * self.window_height
		local scroll_down = action.y > 0.95 * self.window_height

		-- Calculate the scroll amount based on the mouse position
		local scroll_x = 0
		local scroll_y = 0
		local vmatch = false
		local hmatch = false

	elseif action_id == hash("downArrow") then
		if action.pressed then
			self.depth = 1
		elseif action.released and self.depth == 1 then 
			self.depth = 0 
		end
	elseif action_id == hash("upArrow") then
		if action.pressed then
			self.depth = -1
		elseif action.released and self.depth == -1 then 
			self.depth = 0 
		end
	elseif action_id == hash("leftArrow") then
		if action.pressed then
			self.hor = -1
		elseif action.released and self.hor == -1 then 
			self.hor = 0 
		end
	elseif action_id == hash("rightArrow") then
		if action.pressed then
			self.hor = 1
		elseif action.released and self.hor == 1 then 
			self.hor = 0 
		end
	elseif action_id == hash("leanRight") then
		if action.pressed then
			self.lean = -1
		elseif action.released and self.lean == -1 then 
			self.lean = 0 
		end
	elseif action_id == hash("leanLeft") then
		if action.pressed then
			self.lean = 1
		elseif action.released and self.lean == 1 then 
			self.lean = 0
		end
	elseif action_id == hash('sprint') then
		if action.pressed then
			self.sprint = 3
		elseif action.released then
			self.sprint = 1
		end
	elseif action_id == hash("x") then
		if action.pressed then
			self.tilt = 1
		elseif action.released and self.tilt == 1 then 
			self.tilt = 0 
		end
	elseif action_id == hash("z") then
		if action.pressed then
			self.tilt = -1
		elseif action.released and self.tilt == -1 then 
			self.tilt = 0 
		end
	elseif action_id == hash("zoomout") then
		if action.pressed then
			self.updown = 1
		elseif action.released and self.updown == 1 then 
			self.updown = 0 
		end
	elseif action_id == hash("zoomin") then
		if action.pressed then
			self.updown = -1
		elseif action.released and self.updown == -1 then 
			self.updown = 0 
		end
	elseif action_id == hash("debug") and action.pressed then
		pprint('\nDEBUG CAMERA **\npos:',go.get_position(),'rot',go.get_rotation())
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("SCREENSIZE") then
		self.window_width = message.x
		self.window_height = message.y
	elseif message_id == hash('CAMPOS') then
		if message.rot then
			go.animate('main:/CAMERA', 'rotation', go.PLAYBACK_ONCE_FORWARD, message.rot, go.EASING_OUTQUAD, (message.duration or 4),(message.delay or 1))
		end
		if message.pos then
			go.animate('main:/CAMERA', 'position', go.PLAYBACK_ONCE_FORWARD, message.pos, go.EASING_OUTQUAD, (message.duration or 4),(message.delay or 1))
		end
	elseif message_id == hash('INPUT_OFF') then
		msg.post(self.selected, 'release_input_focus')
		msg.post('.', 'release_input_focus')
	elseif message_id == hash('INPUT_ON') then
		msg.post(self.selected, 'acquire_input_focus')
		msg.post('.', 'acquire_input_focus')
	elseif message_id == hash('SELECTED') then
		if self.selected ~= nil and self.selected ~= hash('') then
			if self.selected ~= message.id then
				msg.post(self.selected, 'release_input_focus')
			end
		end
		self.selected = message.id
		msg.post(self.selected, 'acquire_input_focus')
	end
end