components {
  id: "tag"
  component: "/main/camera/tag.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"tag\"\n"
  "mask: \"default\"\n"
  "mask: \"actor\"\n"
  "mask: \"slot\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"box\"\n"
  "  }\n"
  "  data: 1.0\n"
  "  data: 5.0\n"
  "  data: 1.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/dice/d6.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.008\"\n"
  "  material: \"/assets/materials/toon.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/dice/D3.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"DATA_TEXTURE\"\n"
  "    texture: \"/illumination/textures/data.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"LIGHT_TEXTURE\"\n"
  "    texture: \"/illumination/textures/empty.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"NORMAL_TEXTURE\"\n"
  "    texture: \"/illumination/textures/empty.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"SPECULAR_TEXTURE\"\n"
  "    texture: \"/illumination/textures/empty.png\"\n"
  "  }\n"
  "}\n"
  ""
}
