embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/environment/wall.glb\"\n"
  "skeleton: \"/assets/environment/wall.glb\"\n"
  "animations: \"/assets/environment/wall.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"wall\"\n"
  "  material: \"/assets/materials/toon.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/environment/Heist_Wall_Square_1024x673.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 2.0\n"
  "      z: -0.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 5.0\n"
  "  data: 2.0\n"
  "  data: 0.5\n"
  "}\n"
  ""
}
