components {
  id: "figureLoader"
  component: "/main/actors/figureLoader.script"
}
embedded_components {
  id: "LOD0"
  type: "factory"
  data: "prototype: \"/main/figures/human-F1-LO.go\"\n"
  "load_dynamically: true\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_CAPSULE\n"
  "    position {\n"
  "      y: 2.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 2\n"
  "    id: \"hitbox\"\n"
  "  }\n"
  "  data: 0.75\n"
  "  data: 2.5\n"
  "}\n"
  ""
}
